apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: kibana
      release: kibana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kibana
        release: kibana
    spec:
      containers:
      - env:
        - name: ELASTICSEARCH_URL
          value: {{ .Values.elasticsearchurl | default "http://elasticsearch-logging:9200" }}
        image: {{ .Values.kibanaversion | default "kibana:5.4.3" }}
        imagePullPolicy: IfNotPresent
        name: kibana
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
