---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
#  tls:
#  - secretName: ui-ingress
#  backend:
#    serviceName: ui
#    servicePort: 9292
  rules:
  - http:
      paths:
      - path: /*
        backend:
          serviceName: {{ template "ui.fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
