{
 "title": "Business_Logic_Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Rate Panel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(total[5m]) - rate(success[5m])) / rate(total[5m])"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "timeouts" }
   ]
  },
  {
   "title": "Comments rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(comment_count[1h])" }
   ]
  },
  {
   "title": "Posts rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(post_count[1h])" }
   ]
  }
 ]
}