{
 "title": "Telegraf dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Containers running",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_containers_running" }
   ]
  },
  {
   "title": "Containers stopped",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_n_containers_stopped" }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_mem_usage" }
   ]
  }
 ]
}