{
 "title": "Business_Logic_Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Rate Panel",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(total{kubernetes_namespace=~\"$namespace\"}[5m]) - rate(success{kubernetes_namespace=~\"$namespace\"}[5m])) / rate(total{kubernetes_namespace=~\"$namespace\"}[5m])"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "timeouts{kubernetes_namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Comments rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(comment_count{kubernetes_namespace=~\"$namespace\"}[1h])"
    }
   ]
  },
  {
   "title": "Posts rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(post_count{kubernetes_namespace=~\"$namespace\"}[1h])"
    }
   ]
  }
 ]
}