{
 "title": "UI_Service_Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Env", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "UI Request count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ui_request_count{namespace=~\"$namespace\"}"
    }
   ]
  },
  {
   "title": "UI HTTP Requests",
   "type": "graph",
   "description": "Al HTTP requests that UI service receives",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{component=\"ui\",kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP response time 95th percentile",
   "type": "graph",
   "description": "HTTP response time 95th percentile",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket{kubernetes_namespace=~\"$namespace\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "HTTP requests with Error status code",
   "type": "graph",
   "description": "HTTP requests with Error status code",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\",kubernetes_namespace=~\"$namespace\"}[1m])"
    }
   ]
  }
 ]
}